[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cat-box = "22.6.21"
rand = "0.8.5"
sdl2 = "0.35.2"

[features]
default = []
static = ["cat-box/static"]
